=== Vault1996/KBRS/web/data/OldCards.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/OldCards"
        xmlns:tns="http://www.example.com/OldCards"
        elementFormDefault="qualified"
>
    <element name="oldCard" type="tns:OldCard" abstract="true"/>
    <element name="postCard" type="tns:PostCard" substitutionGroup="tns:oldCard"/>
    <element name="soundCard" type="tns:SoundCard" substitutionGroup="tns:oldCard"/>

    <element name="oldCards">
        <complexType>
            <sequence>
                <element ref="tns:oldCard" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <!-- Базовый класс -->
    <complexType name="OldCard">
        <sequence>
            <element name="Thema" type="tns:thema"/>
            <element name="Type" type="tns:type"/>
            <element name="Country" type="tns:country"/>
            <element name="Year" type="tns:year"/>
            <element name="Valuable" type="boolean"/>
        </sequence>
        <!-- Атрибут уникальный ID -->
        <attribute name="Id" type="tns:id" use="required"/>
        <attribute name="Author" type="string" use="optional" default="None"/>
    </complexType>
    <!-- Postcard -->
    <complexType name="PostCard">
        <complexContent>
            <extension base="tns:OldCard">
                <sequence>
                    <element name="Message" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <!-- SoundCard -->
    <complexType name="SoundCard">
        <complexContent>
            <extension base="tns:OldCard">
                <sequence>
                    <element name="Song" type="string"/>
                    <element name="Format" type="tns:format"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

<!-- Типы данных -->
    <simpleType name="thema">
        <restriction base="string">
            <enumeration value="Landscape"/>
            <enumeration value="Nature"/>
            <enumeration value="People"/>
            <enumeration value="Religion"/>
            <enumeration value="Sport"/>
            <enumeration value="Architecture"/>
        </restriction>
    </simpleType>
    <simpleType name="type">
        <restriction base="string">
            <enumeration value="Celebration"/>
            <enumeration value="Adv"/>
            <enumeration value="Usual"/>
        </restriction>
    </simpleType>
    <simpleType name="country">
        <restriction base="string">
            <enumeration value="Russia"/>
            <enumeration value="Belarus"/>
            <enumeration value="Great Britain"/>
            <enumeration value="Ukraine"/>
        </restriction>
    </simpleType>
    <simpleType name="year">
        <restriction base="gYear">
            <minInclusive value="1000"/>
            <maxExclusive value="2016"/>
        </restriction>
    </simpleType>
    <simpleType name="id">
        <restriction base="ID">
            <pattern value="ID_(\d){1,12}"/>
        </restriction>
    </simpleType>
    <simpleType name="format">
        <restriction base="string">
            <enumeration value="mp3"/>
            <enumeration value="wav"/>
        </restriction>
    </simpleType>
<!-- ======================== -->
</schema>

=== Vault1996/KBRS/web/data/OldCards.xml
<?xml version="1.0" encoding="UTF-8"?>

<oldCards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/OldCards"
          xsi:schemaLocation="http://www.example.com/OldCards OldCards.xsd">

    <postCard Id="ID_123">
        <Thema>Architecture</Thema>
        <Type>Usual</Type>
        <Country>Belarus</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <postCard Id="ID_323" Author="Arthur">
        <Thema>Landscape</Thema>
        <Type>Usual</Type>
        <Country>Belarus</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <soundCard Id="ID_231">
        <Thema>Nature</Thema>
        <Type>Celebration</Type>
        <Country>Great Britain</Country>
        <Year>2012</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>wav</Format>
    </soundCard>
    <soundCard Author="Liza" Id="ID_251">
        <Thema>People</Thema>
        <Type>Celebration</Type>
        <Country>Russia</Country>
        <Year>2012</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>mp3</Format>
    </soundCard>
    <postCard Id="ID_1124">
        <Thema>Religion</Thema>
        <Type>Adv</Type>
        <Country>Belarus</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <postCard Id="ID_13213" Author="Arthur">
        <Thema>Sport</Thema>
        <Type>Usual</Type>
        <Country>Ukraine</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <soundCard Id="ID_9991">
        <Thema>Architecture</Thema>
        <Type>Celebration</Type>
        <Country>Great Britain</Country>
        <Year>1456</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>mp3</Format>
    </soundCard>
    <soundCard Author="Liza" Id="ID_823">
        <Thema>Architecture</Thema>
        <Type>Celebration</Type>
        <Country>Great Britain</Country>
        <Year>2012</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>wav</Format>
    </soundCard>
    <postCard Id="ID_12333">
        <Thema>Architecture</Thema>
        <Type>Usual</Type>
        <Country>Belarus</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <postCard Id="ID_523" Author="Arthur">
        <Thema>Architecture</Thema>
        <Type>Usual</Type>
        <Country>Belarus</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <soundCard Id="ID_715">
        <Thema>Architecture</Thema>
        <Type>Celebration</Type>
        <Country>Great Britain</Country>
        <Year>2012</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>mp3</Format>
    </soundCard>
    <soundCard Author="Liza" Id="ID_345">
        <Thema>Architecture</Thema>
        <Type>Celebration</Type>
        <Country>Great Britain</Country>
        <Year>2012</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>mp3</Format>
    </soundCard>
    <postCard Id="ID_123143">
        <Thema>Architecture</Thema>
        <Type>Usual</Type>
        <Country>Belarus</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <postCard Id="ID_18484" Author="Arthur">
        <Thema>Architecture</Thema>
        <Type>Usual</Type>
        <Country>Belarus</Country>
        <Year>1023</Year>
        <Valuable>true</Valuable>
        <Message>Hello world!</Message>
    </postCard>
    <soundCard Id="ID_9123">
        <Thema>Architecture</Thema>
        <Type>Celebration</Type>
        <Country>Great Britain</Country>
        <Year>2012</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>mp3</Format>
    </soundCard>
    <soundCard Author="Liza" Id="ID_8800">
        <Thema>Architecture</Thema>
        <Type>Celebration</Type>
        <Country>Great Britain</Country>
        <Year>2012</Year>
        <Valuable>true</Valuable>
        <Song>Hello</Song>
        <Format>mp3</Format>
    </soundCard>

</oldCards>
